//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public int Length { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> StartPlayingTime { get; set; }
        public Nullable<System.DateTime> EndPlayingTime { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
        public string Language { get; set; }
        public string img_path { get; set; }
        public string Director { get; set; }
        public string Scriptwriter { get; set; }
        public string Actor { get; set; }
        public string Introduce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
