//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int ScheduleID { get; set; }
        public string SiteIDs { get; set; }
        public System.DateTime DateTime { get; set; }
        public int PaymentId { get; set; }
        public string States { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
